[project]
authors = [{ name = "jlnav", email = "jnavarro@anl.gov" }]
dependencies = ["libensemble>=1.5.0,<2"]
name = "ensemblesweep"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel", "pip>=24.3.1,<27", "setuptools>=75.1.0,<83"]

[tool.setuptools.packages.find]
where = ["."]
include = ["ensemblesweep*"]

[tool.setuptools.dynamic]
version = { attr = "ensemblesweep.version.__version__" }

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.environments]
default = []
dev = ["dev"]

[tool.pixi.pypi-dependencies]
ensemblesweep = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
libensemble = ">=1.5.0,<2"

[tool.pixi.feature.dev.dependencies]
pre-commit = ">=4.5.1,<5"
ruff = ">=0.15.2,<0.16"
pip = ">=26.0.1,<27"

[dependency-groups]
dev = ["wat>=0.7.0,<0.8"]
